"""Update User model: rename habits to my_past

Revision ID: dc83e21db708
Revises: 9ea8070e4913
Create Date: 2024-06-30 22:19:57.636901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc83e21db708'
down_revision = '9ea8070e4913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_past', sa.String(length=100), nullable=True))
        batch_op.drop_column('habits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habits', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('my_past')

    # ### end Alembic commands ###
